apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-client-config-map
data:
  PUBLIC_URL: "/"
  AWS_REGION: {{ .Values.cognito.region | quote }}
  COGNITO_USER_POOL_ID: {{ .Values.cognito.userPoolId | quote }}
  COGNITO_USER_POOL_WEB_CLIENT_ID: {{ .Values.cognito.userPoolWebClientId | quote }}
  API_URI: {{ .Values.env.apiUri }}
  WS_URI: {{ .Values.env.wsUri }}
  GOOGLE_ANALYTICS_ID: {{ .Values.env.googleAnalyticsId }}
