apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  PUBLIC_URL: "/"
  AWS_REGION: {{ .Values.cognito.region | quote }}
  COGNITO_USER_POOL_ID: {{ .Values.cognito.userPoolId | quote }}
  COGNITO_USER_POOL_WEB_CLIENT_ID: {{ .Values.cognito.userPoolWebClientId | quote }}
  API_URI: https://{{ .Values.api.host }}{{ .Values.api.prefix }}
  WS_URI: wss://{{ .Values.api.host }}{{ .Values.api.prefix }}
  GOOGLE_ANALYTICS_ID: {{ .Values.client.googleAnalyticsId }}
