apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-client-virtual-service
spec:
  hosts:
    - {{ .Values.env.host }}
  gateways:
    - {{ .Values.gateway.include | ternary (print .Release.Name "-client-gateway") .Values.gateway.name }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 80
            host: {{ .Release.Name }}-client-svc
