version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Packages
          command: |
            npm ci
      - run:
          name: Run Unit Tests
          command: |
            npm t
      - run:
          name: Build
          command: |
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build/*
            - env.schema.js
            - Dockerfile
            - .dockerignore

  publish-helm:
    docker:
      - image: hypnoglow/helm-s3:master-helm3.4
    shell: /bin/sh -leo pipefail
    environment:
      - BASH_ENV: /etc/profile
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            TAG="${CIRCLE_TAG:1}"
            echo $TAG
            echo "export TAG=$TAG" >> $BASH_ENV
      - run:
          name: Add Repo
          command: |
            helm repo add stingyvegan-s3 s3://helm.stingyvegan.com
            helm repo list
      - run:
          name: Package Chart
          command: |
            helm dependency build ./helm
            helm package ./helm --version=$TAG --app-version=$TAG
      - run:
          name: Publish Chart
          command: |
            helm s3 push --relative ./sv-user-client-$TAG.tgz stingyvegan-s3

  publish:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Setup Environment Variables
          command: |
            REGISTRY=$DOCKER_REGISTRY_URL/stingyvegan/user-client
            echo $REGISTRY
            echo "export REGISTRY=$REGISTRY" >> $BASH_ENV
            TAG=$CIRCLE_TAG
            echo $TAG
            echo "export TAG=$TAG" >> $BASH_ENV
      - run:
          name: Run Docker Build
          command: |
            docker build -t $REGISTRY:$TAG .
      - run:
          name: Push Docker Image
          command: |
            echo $CR_PAT | docker login $DOCKER_REGISTRY_URL -u $DOCKER_USERNAME --password-stdin
            docker push $REGISTRY:$TAG

  publish-latest:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Setup Environment Variables
          command: |
            REGISTRY=$DOCKER_REGISTRY_URL/stingyvegan/user-client
            echo $REGISTRY
            echo "export REGISTRY=$REGISTRY" >> $BASH_ENV
            TAG=$CIRCLE_TAG
            echo $TAG
            echo "export TAG=$TAG" >> $BASH_ENV
      - run:
          name: Run Docker Build
          command: |
            docker build -t $REGISTRY:$TAG .
            docker tag $REGISTRY:$TAG $REGISTRY:latest
      - run:
          name: Push Docker Image
          command: |
            echo $CR_PAT | docker login $DOCKER_REGISTRY_URL -u $DOCKER_USERNAME --password-stdin
            docker push $REGISTRY:$TAG
            docker push $REGISTRY:latest

workflows:
  version: 2
  ci:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/

      - publish:
          requires:
            - test
          filters:
            tags:
              only: /v([0-9])*.([0-9])*.([0-9])*-.*/
            branches:
              ignore: /.*/
          context: stingyvegan-github

      - publish-latest:
          requires:
            - test
          filters:
            tags:
              only: /v([0-9])*.([0-9])*.([0-9])*/
            branches:
              ignore: /.*/
          context: stingyvegan-github

      - publish-helm:
          requires:
            - test
          filters:
            tags:
              only: /v([0-9])*.([0-9])*.([0-9])*.*/
            branches:
              ignore: /.*/
          context: s3-helm-deploy
