version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Packages
          command: |
            npm ci
      - run:
          name: Run Unit Tests
          command: |
            npm t
      - run:
          name: Build
          command: |
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build/*
            - env.schema.js

workflows:
  version: 2
  ci:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
