cognito:
  region: ap-southeast-2
  userPoolId: ap-southeast-2_zoRQDzN1a
  userPoolWebClientId: 776sok3fkftpnvab93d4clk5d7

env:
  apiUri: http://api.local.stingyvegan.com/api
  wsUri: ws://api.local.stingyvegan.com/api
  host: local.stingyvegan.com
  googleAnalyticsId: UA-133927969-1

image:
  registry: ghcr.io/stingyvegan/user-client
  version: v0.3.1
  registrySecretName: registry-github-stingyvegan

gateway:
  include: true
  # name: external-gateway # Provide only if include is false
